version: '3.8'
services:
  frontend-out:
    build: ./frontend-out
    ports:
      - "8087:80"
  backend:
    build: ./backend
    ports:
      - "3017:3017"
  backend-console:
    build: ./backend-console
    ports:
      - "8088:80"
